name: CI

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - run: npm run build
      - name: remove all file
        uses: appleboy/ssh-action@master
        with:
          host: "16.163.177.75"
          username: ubuntu
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ~
            cd /var/www/chatapp/html
            rm -rf *
      - name: copy file to remote server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./build
          remote_path: /var/www/chatapp/html
          remote_host: "16.163.177.75"
          remote_user: ubuntu
          remote_key: ${{ secrets.SSHKEY }}

            